### ISSUE TITLE
Changes to NewStreamWatcher breaks compatibility with k8s.io/client-go/rest library

### ISSUE THREAD

**Issue by tmessinis** [kubernetes/apimachinery#63]
Hello,

I began getting the following error when importing the `k8s.io/client-go/rest` package.

```
go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

Upon doing some investigation it seems that the NewStreamWatcher function in was changed fairly recently:
https://github.com/kubernetes/apimachinery/commit/6bfc4729640e1b788e991515a8ea4e16504c3a5d#diff-13d4c1aef2b5ff5ac3d279505679acc0L52

This change though wasn't reflected in the call to NewStreamWatcher in request.go:
https://github.com/kubernetes/client-go/blob/master/rest/request.go#L598

It seems that only a single decoder struct gets returned from the NewDecoder function:
https://github.com/kubernetes/client-go/blob/master/rest/watch/decoder.go#L39

Is this something that's planned to be fixed?

**Comment by liggitt** [comment]
> This change though wasn't reflected in the call to NewStreamWatcher in request.go:
> https://github.com/kubernetes/client-go/blob/master/rest/request.go#L598

That apimachinery change is in the master branch, and the call you linked to is updated in client-go on master.

The client-go@v11.0.0 tag works with the release-1.14 branch of apimachinery:

https://github.com/kubernetes/apimachinery/blob/release-1.14/pkg/watch/streamwatcher.go#L51-L52

Ensure you are using the release-1.14 branch of apimachinery.

/close

**Comment by draveness** [comment]
Met another problem after updating to release 1.14 branch

```go
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/metrics/client_go_adapter.go:201:55: cannot use composite literal (type workqueueMetricsProvider) as type workqueue.MetricsProvider in argument to workqueue.SetProvider:
	workqueueMetricsProvider does not implement workqueue.MetricsProvider (missing NewDeprecatedAddsMetric method)
# sigs.k8s.io/controller-runtime/pkg/leaderelection
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/leaderelection/leader_election.go:83:25: not enough arguments in call to resourcelock.New
	have (string, string, string, "k8s.io/client-go/kubernetes/typed/core/v1".CoreV1Interface, resourcelock.ResourceLockConfig)
	want (string, string, string, "k8s.io/client-go/kubernetes/typed/core/v1".CoreV1Interface, "k8s.io/client-go/kubernetes/typed/coordination/v1".CoordinationV1Interface, resourcelock.ResourceLockConfig)
```

go.mod

```go
module github.com/draveness/proxier

go 1.12

replace k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20190404173353-6a84e37a896d

require (
	github.com/appscode/jsonpatch v0.0.0-20190108182946-7c0e3b262f30 // indirect
	github.com/coreos/prometheus-operator v0.29.0 // indirect
	github.com/dgrijalva/jwt-go v3.2.0+incompatible // indirect
	github.com/docker/distribution v2.7.1+incompatible // indirect
	github.com/emicklei/go-restful v2.9.3+incompatible // indirect
	github.com/go-logr/logr v0.1.0 // indirect
	github.com/go-logr/zapr v0.1.1 // indirect
	github.com/go-openapi/spec v0.19.0
	github.com/golang/groupcache v0.0.0-20190129154638-5b532d6fd5ef // indirect
	github.com/google/btree v1.0.0 // indirect
	github.com/imdario/mergo v0.3.7 // indirect
	github.com/json-iterator/go v1.1.6 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.1 // indirect
	github.com/opencontainers/go-digest v1.0.0-rc1 // indirect
	github.com/operator-framework/operator-sdk v0.7.0
	github.com/pkg/errors v0.8.1
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/pflag v1.0.3
	github.com/stretchr/testify v1.3.0
	go.uber.org/zap v1.9.1 // indirect
	golang.org/x/crypto v0.0.0-20190411191339-88737f569e3a // indirect
	golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a // indirect
	golang.org/x/sync v0.0.0-20190412183630-56d357773e84
	golang.org/x/time v0.0.0-20190308202827-9d24e82272b4 // indirect
	google.golang.org/appengine v1.5.0 // indirect
	gopkg.in/inf.v0 v0.9.1 // indirect
	gopkg.in/square/go-jose.v2 v2.3.1 // indirect
	k8s.io/api v0.0.0-20190413052509-3cc1b3fb6d0f
	k8s.io/apiextensions-apiserver v0.0.0-20190413053546-d0acb7a76918 // indirect
	k8s.io/apimachinery v0.0.0-20190413052414-40a3f73b0fa2
	k8s.io/client-go v11.0.0+incompatible
	k8s.io/cloud-provider v0.0.0-20190413054028-113aea9f21af // indirect
	k8s.io/kube-openapi v0.0.0-20190401085232-94e1e7b7574c
	k8s.io/kubernetes v1.14.1
	k8s.io/utils v0.0.0-20190308190857-21c4ce38f2a7 // indirect
	sigs.k8s.io/controller-runtime v0.1.10
	sigs.k8s.io/testing_frameworks v0.1.1 // indirect
)
```

**Comment by liggitt** [comment]
it looks like controller-runtime is in the process of updating to latest kubernetes levels (https://github.com/kubernetes-sigs/controller-runtime/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+bump)

until then, if controller-runtime is a dependency of yours, you may need to remain on 1.13.x levels

/close

**Comment by pawel-milewski-pr** [comment]
/reopen   
just install client-go, straight off the box its not working

**Comment by tomklino** [comment]
@liggitt "Ensure you are using the release-1.14 branch of apimachinery."
how?

currently just developing a tiny app, trying it with `go run` and and getting the same issue. saw you replied similarly on several issues and it's not clear to me

**Comment by liggitt** [comment]
Something like this:
1. Use go 1.12+
2. `export GO111MODULE=on`
3. In your go.mod file, specify the versions of client-go/api/apimachinery you want, e.g.:

```
require (
  k8s.io/client-go kubernetes-1.16.0
  k8s.io/api kubernetes-1.16.0
  k8s.io/apimachinery kubernetes-1.16.0
)
```

See https://github.com/kubernetes/client-go/blob/master/INSTALL.md for details

**Comment by jose-sanchezm** [comment]
Suddenly my project that was building fine before stopped doing it. I've tried everything:

```
$ go get -u k8s.io/client-go@kubernetes-1.16.0
go: finding k8s.io/client-go kubernetes-1.16.0
$
```

Then I replace the whole require directive of my go.mod with

```
require (
  k8s.io/client-go kubernetes-1.16.0
  k8s.io/api kubernetes-1.16.0
  k8s.io/apimachinery kubernetes-1.16.0
)
```

But then when I execute ```go build```

```
$ go build                                                                     
go: finding k8s.io/client-go kubernetes-1.16.0
go: finding k8s.io/api kubernetes-1.16.0
go: finding k8s.io/apimachinery kubernetes-1.16.0
go: finding github.com/DITAS-Project/blueprint-go latest
go: finding github.com/xdg/scram latest
# k8s.io/client-go/rest
../../../go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)
```

The whole require directive gets replaced with incompatible versions of client-go it seems:

```
require(
....
	k8s.io/api v0.0.0-20191003035645-10e821c09743
	k8s.io/apimachinery v0.0.0-20191003115452-c31ffd88d5d2
	k8s.io/client-go v11.0.0+incompatible
)
```

How can I force it to get the specific version I'm specifying instead of having it replaced on every go build?

**Comment by liggitt** [comment]
> How can I force it to get the specific version I'm specifying instead of having it replaced on every go build?

1. resolve the versions you want:
```
curl -s https://proxy.golang.org/k8s.io/api/@v/kubernetes-1.16.0.info | jq -r .Version
curl -s https://proxy.golang.org/k8s.io/apimachinery/@v/kubernetes-1.16.0.info | jq -r .Version
curl -s https://proxy.golang.org/k8s.io/client-go/@v/kubernetes-1.16.0.info | jq -r .Version
```

> ```
> v0.0.0-20190918155943-95b840bb6a1f
> v0.0.0-20190913080033-27d36303b655
> v0.0.0-20190918160344-1fbdaa4c8d90
> ```
> 

2. add replace directives in your go.mod file to pin to those versions:
```
replace k8s.io/api => k8s.io/api v0.0.0-20190918155943-95b840bb6a1f
replace k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20190913080033-27d36303b655
replace k8s.io/client-go => k8s.io/client-go v0.0.0-20190918160344-1fbdaa4c8d90
```

**Comment by jose-sanchezm** [comment]
Thanks. That worked. Now my project builds again. Go modules are all but intuitive.

**Comment by liggitt** [comment]
> Go modules are all but intuitive

That's somewhat true, but they mostly assume sane things will happen with semantically versioned modules. Kubernetes is not in a good place from that perspective, but unfortunately the changes required to align kubernetes with the requirements of go modules are even more disruptive (e.g. changing all import paths for client-go/api/apimachinery).
