### ISSUE TITLE
Go 1.10: selector_test.go:390: Errorf format %t arg result.Empty is a func value, not called

### ISSUE THREAD

**Issue by nim-nim** [kubernetes/apimachinery#37]
Release 1.7.15 does not pass unit tests with Go 1.10. At least:

```
+ GOPATH=/builddir/build/BUILD/apimachinery-kubernetes-1.7.15/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro  '\'''
# k8s.io/apimachinery/pkg/fields
./selector_test.go:390: Errorf format %t arg result.Empty is a func value, not called
FAIL	k8s.io/apimachinery/pkg/fields [build failed]
```

**Comment by liggitt** [comment]
go 1.10 will not be supported until kube 1.11

See https://github.com/kubernetes/kubernetes/pull/60597

/close

**Comment by nim-nim** [comment]
Unfortunately, others projects import ancient kubernetes clients (1.7), and at the same time build with recent Go releases like 1.10. So ancient kubernetes clients have to work with recent compilers or the rest of the ecosystem won't move to recent Go compilers (or, more accurately, will just disable unit tests)

IIRC some of those like heapster are used by parts of kubernetes itself.
